[package]
name = "netshield-ebpf"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]
aya-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-log-ebpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
network-types = "0.0.8"
netshield-ebpf-common = { path = "./netshield-ebpf-common" }
bytemuck = { version = "1.14", default-features = false, features = ["derive"] }

[lib]
crate-type = ["cdylib"]
path = "src/main.rs"

[profile.dev]
opt-level = 2
debug = false
lto = true
panic = "abort"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

# Custom build to generate .o file
[package.metadata.bpf]
target_dir = "target"
